# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleFLC <- function(BtY, Beta, Psi, BtB, Omega, lambda, sigmat2) {
    .Call('_fosr_sampleFLC', PACKAGE = 'fosr', BtY, Beta, Psi, BtB, Omega, lambda, sigmat2)
}

sampleFLC_orthog <- function(BtY, Beta, Psi, Omega, lambda, sigmat2) {
    .Call('_fosr_sampleFLC_orthog', PACKAGE = 'fosr', BtY, Beta, Psi, Omega, lambda, sigmat2)
}

sampleFLC_cons <- function(BtY, Beta, Psi, BtB, Omega, BtCon, lambda, sigmat2) {
    .Call('_fosr_sampleFLC_cons', PACKAGE = 'fosr', BtY, Beta, Psi, BtB, Omega, BtCon, lambda, sigmat2)
}

sampleFLC_cons_1 <- function(BtY, Beta, Psi, BtB, Omega, BtCon, lambda, sigmat2) {
    .Call('_fosr_sampleFLC_cons_1', PACKAGE = 'fosr', BtY, Beta, Psi, BtB, Omega, BtCon, lambda, sigmat2)
}

sampleFLC_1 <- function(BtY, Beta, Psi, BtB, Omega, lambda, sigmat2) {
    .Call('_fosr_sampleFLC_1', PACKAGE = 'fosr', BtY, Beta, Psi, BtB, Omega, lambda, sigmat2)
}

